# Generated by Django 2.2.1 on 2019-10-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_job_management_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_management',
            old_name='birth_date',
            new_name='expiry_date',
        ),
    ]
