# Generated by Django 2.2.1 on 2019-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20191017_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtable',
            name='profile_video',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
