# Generated by Django 2.2.1 on 2019-11-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0008_newtable_profile_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(blank=True, max_length=100)),
                ('Question_Domain', models.CharField(blank=True, max_length=100)),
                ('question', models.CharField(blank=True, max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('choice_two', models.CharField(blank=True, max_length=100)),
                ('choice_three', models.CharField(blank=True, max_length=100)),
                ('choice_four', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invitation_Code', models.CharField(max_length=6, unique=True)),
                ('Interviewr_name', models.CharField(blank=True, max_length=100)),
                ('Interview_Email', models.EmailField(blank=True, max_length=100)),
                ('Interviewr_Resume', models.ImageField(blank=True, upload_to='user_cv')),
                ('Interviewr_Experience', models.CharField(blank=True, max_length=200)),
                ('Interview_expiry_date', models.DateField(blank=True, null=True)),
                ('Interviewr_Contact_Number', models.CharField(blank=True, max_length=15)),
                ('Interviewr_Last_Company', models.CharField(blank=True, max_length=50)),
                ('Interviewr_Country', models.CharField(blank=True, max_length=50)),
                ('Interview_Profile', models.URLField(blank=True, max_length=100)),
                ('jobtitle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.Job_Management')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
