# Generated by Django 2.2.1 on 2019-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_interview_invite_question_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_bank',
            name='question_id',
        ),
        migrations.AddField(
            model_name='question_bank',
            name='Invitation_Code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='question_bank',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
