# Generated by Django 2.2.1 on 2019-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20191103_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='Invitation_Code',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
