# Generated by Django 2.2.1 on 2019-11-03 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0011_auto_20191103_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_bank',
            old_name='Invitation_Code',
            new_name='Question_Bank_id',
        ),
        migrations.CreateModel(
            name='Question_BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_BankDetail_id', models.CharField(default='', max_length=6, unique=True)),
                ('Department', models.CharField(blank=True, max_length=100)),
                ('Question_Domain_Detail', models.CharField(blank=True, max_length=100)),
                ('question', models.CharField(blank=True, max_length=100)),
                ('detail_answer', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
