# Generated by Django 2.2.1 on 2019-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_remove_question_bankdetail_detail_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='Question_Bank_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='question_bankdetail',
            name='Question_BankDetail_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
