# Generated by Django 2.2.1 on 2019-11-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_remove_question_bankdetail_q_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_bank',
            name='Question_Bank_id',
        ),
    ]
