# Generated by Django 2.2.1 on 2019-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_remove_question_bank_question_bank_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Detail_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(blank=True, max_length=100)),
                ('Answer_Name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
