# Generated by Django 2.2.1 on 2019-11-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_question_detail_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_detail_answer',
            name='Code_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question_detail_answer',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question_detail_answer',
            name='Answer_Name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
