# Generated by Django 2.2.1 on 2019-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_auto_20191107_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_invite',
            name='jobtitle',
            field=models.CharField(max_length=100),
        ),
    ]
