# Generated by Django 2.2.1 on 2019-11-06 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_auto_20191107_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_invite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
