# Generated by Django 2.2.1 on 2019-11-06 19:45

from django.db import migrations, models
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_auto_20191107_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_invite',
            name='Invitation_Code',
            field=models.CharField(default=first_app.models.f, max_length=6, unique=True),
        ),
    ]
