# Generated by Django 2.2.1 on 2019-11-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20191107_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_detail_answer',
            name='Negative_Emotions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_detail_answer',
            name='Neutral_Emotions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_detail_answer',
            name='positive_Emotions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_detail_answer',
            name='Answer_Name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question_detail_answer',
            name='Code_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_detail_answer',
            name='Question_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_detail_answer',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
