# Generated by Django 2.2.1 on 2019-11-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_auto_20191107_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtable',
            name='profile_video',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
