# Generated by Django 2.2.1 on 2019-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_auto_20191110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_invite',
            name='Interview_Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interview_invite',
            name='Interviewr_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='Department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='Question_Domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='choice_two',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bankdetail',
            name='Department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bankdetail',
            name='Question_Domain_Detail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_bankdetail',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
