# Generated by Django 2.2.1 on 2019-11-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_auto_20191110_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview_invite',
            name='id',
        ),
        migrations.AddField(
            model_name='interview_invite',
            name='detail_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
