# Generated by Django 2.2.1 on 2019-11-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_codecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecheck',
            name='Code_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
